appName: hello-twinape

hazelcast:
  filePath: "/home/rob/Work/TwinApe/git/hello-twinape/app/config/hazelcast-local.xml"

vertx:
  preferNativeTransport: ${VERTX_PREFER_NATIVE_TRANSPORT | false}
# eventBus:

metrics:
  host: 0.0.0.0
  port: 5555
  path: /metrics
  enabledLabels:
    - EB_ADDRESS
    - EB_SIDE
    - EB_FAILURE
    - HTTP_METHOD
    - HTTP_ROUTE
    - HTTP_CODE
  disabledDomains:
    - NAMED_POOLS
    - DATAGRAM_SOCKET
    - NET_CLIENT
    - NET_SERVER
    - HTTP_SERVER

publicHttp:
  host: ${PUBLIC_HTTP_HOST | 0.0.0.0}
  port: ${PUBLIC_HTTP_PORT | 9001}
  path: ${PUBLIC_HTTP_PATH | /api}
  cors:
    allowAll: ${PUBLIC_HTTP_CORS_ALLOW_ALL | true}

#mySql:
#  uri: mysql-steady://postgres:12345678@localhost:5432/daily

pgSql:
  uri: postgres-steady://postgres:12345678@localhost:5432/daily

kafka:
  bootstrapServers: localhost:9092